apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: unity
    spec:
      containers:
        - name: unity
          image: abhijithgopal/unity:v2
          imagePullPolicy: Always
          ports:
          - containerPort: 4567
            name: http
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              scheme: HTTP
              path: /alive
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              scheme: HTTP
              path: /alive
              port: http
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "100Mi"
          envFrom:
          - configMapRef:
              name: unity
---
apiVersion: v1
kind: Service
metadata:
  name: unity
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 4567
    targetPort: 4567
    protocol: TCP
  selector:
    name: unity
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unity
data:
  QUEUE_HOST: "redis.default.svc.cluster.local"
  QUEUE_PORT: "6379"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:4.0
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
  ports:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
