version: "3"
services:
  app:
    image: unity:v3
    build: .
    ports:
    - "4567:4567"
    depends_on:
      - "redis"
    networks:
      - unity
  redis:
    image: redis
    networks:
      - unity

networks:
  unity:
    driver: bridge
