version: "3"
services:
  app:
    image: app:v1
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
    - "0.0.0.0:4567:4567"
    depends_on:
      - "redis"
    environment:
      - QUEUE_HOST=redis
    networks:
      - app
  redis:
    build:
      context: ./
      dockerfile: Dockerfile.queue
    image: redis
    networks:
      - app

networks:
  app:
    driver: bridge
