version: "3"
services:
  app:
    image: unity:v1
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
    - "0.0.0.0:4567:4567"
    depends_on:
      - "redis"
    environment:
      - HOST=redis
    networks:
      - unity
  redis:
    build:
      context: ./
      dockerfile: Dockerfile.queue
    image: redis
    networks:
      - unity

networks:
  unity:
    driver: bridge
